config/routes.rb
Eventmanager::Application.routes.draw do
  resources :contests

  resources :venues

  resources :meetings

  resources :sponsors

  resources :exhibitors

  resources :exhibitor_categories
  
  root :to => "venues#index"

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_accessible :name, :start_date, :end_time, :exhibitors, :contests
  
  validates :name, :presence => true
  validates :start_date, :presence => true
  validates :end_time, :presence => true
  
  belongs_to :venue
  has_and_belongs_to_many :sponsors
  has_many :exhibitors, :through => :sponsors
  has_many :contests
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all

    respond_to do |format|
      format.html # /.erb
      format.json { render json: @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :venue_id %><br />
    <%= f.collection_select :venue_id, Venue.all.collect, :id, :name, :prompt => "Select a Venue" %>
  </div>
  <div class="field">
    <%= f.label "Sponsors" %><br />
    <% for sponsor in Sponsor.all %>
      <%= check_box_tag 'meeting[sponsor_ids][]', sponsor.id, 
      @meeting.sponsor_ids.include?(sponsor.id), :id => dom_id(sponsor) %>
      <%= label_tag dom_id(sponsor), sponsor.exhibitor.name, :class => "check_box_label" %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<h1>Listing meetings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Start date</th>
    <th>End time</th>
    <th>Venue</th>
    <th>Sponsors</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meetings.each do |meeting| %>
  <tr>
    <td><%= meeting.name %></td>
    <td><%= meeting.start_date %></td>
    <td><%= meeting.end_time %></td>
    <td><%= meeting.venue.name %></td>
    <td><% meeting.exhibitors.each do |c| %>
          <%= raw( "<li>" + c.name + "</li>") %>
        <% end %>
    </td>
    <td><%= link_to 'Show', meeting %></td>
    <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
    <td><%= link_to 'Destroy', meeting, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<div id="bodyRightPan">
	<div class="bodyRightPanBlock">
      <h2>Venue:</h2>
      <p><%= link_to @meeting.venue.name, @meeting.venue %><br />
      <%= @meeting.venue.address %><br />
      <%= @meeting.venue.city %>, <%= @meeting.venue.state %>&nbsp;&nbsp;<%= @meeting.venue.zip %>
      </p>
	</div>
	<div class="bodyRightPanBlock" style="margin-top:2.5em;">
      <h2>Sponsors:</h2>
        <ul>
        <% @meeting.exhibitors.each do |c| %>
          <%= link_to c.name, c %><br />
        <% end %>
        </ul>
	</div>
</div>
<h1>Meeting Details</h1>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @meeting.name %>
</p>

<p>
  <b>Start date:</b>
  <%= @meeting.start_date %>
</p>

<p>
  <b>End time:</b>
  <%= @meeting.end_time %>
</p>




<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>