config/routes.rb
Eventmanager::Application.routes.draw do
  resources :contests

  resources :venues

  resources :meetings

  resources :sponsors

  resources :exhibitors

  resources :exhibitor_categories
  
  root :to => "venues#index"

end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  attr_accessible :url, :logo, :meetings, :meetings_ids
  
  validates :url, :presence => true
  validates :logo, :presence => true
  
  has_one :exhibitor
  has_and_belongs_to_many :meetings
  has_many :contests
  
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  # GET /sponsors
  # GET /sponsors.json
  def index
    @sponsors = Sponsor.all

    respond_to do |format|
      format.html # /.erb
      format.json { render json: @sponsors }
    end
  end

  # GET /sponsors/1
  # GET /sponsors/1.json
  def show
    @sponsor = Sponsor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sponsor }
    end
  end

  # GET /sponsors/new
  # GET /sponsors/new.json
  def new
    @sponsor = Sponsor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sponsor }
    end
  end

  # GET /sponsors/1/edit
  def edit
    @sponsor = Sponsor.find(params[:id])
  end

  # POST /sponsors
  # POST /sponsors.json
  def create
    @sponsor = Sponsor.new(params[:sponsor])

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully created.' }
        format.json { render json: @sponsor, status: :created, location: @sponsor }
      else
        format.html { render action: "new" }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sponsors/1
  # PUT /sponsors/1.json
  def update
    @sponsor = Sponsor.find(params[:id])

    respond_to do |format|
      if @sponsor.update_attributes(params[:sponsor])
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.json
  def destroy
    @sponsor = Sponsor.find(params[:id])
    @sponsor.destroy

    respond_to do |format|
      format.html { redirect_to sponsors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_form.html.erb
<%= form_for(@sponsor) do |f| %>
  <% if @sponsor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sponsor.errors.count, "error") %> prohibited this sponsor from being saved:</h2>

      <ul>
      <% @sponsor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label "Meetings" %><br />
    <% for meeting in Meeting.all %>
      <%= check_box_tag 'meeting[meeting_ids][]', meeting.id, 
      @sponsor.meeting_ids.include?(meeting.id), :id => dom_id(meeting) %>
      <%= label_tag dom_id(meeting), meeting.name, :class => "check_box_label" %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sponsors/edit.html.erb
<h1>Editing sponsor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sponsor %> |
<%= link_to 'Back', sponsors_path %>

app/views/sponsors/index.html.erb
<h1>Listing sponsors</h1>

<table>
  <tr>
  	<th>Exhibitor</th>
    <th>Url</th>
    <th>Logo</th>
    <th>Meetings</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sponsors.each do |sponsor| %>
  <tr>
    <td><%= sponsor.exhibitor.name %></td>
    <td><%= sponsor.url %></td>
    <td><%= sponsor.logo %></td>
    <td><% for meeting in sponsor.meetings %>
      <%= raw( meeting.name + "<br />") %>
    <% end %>
    </td>
    <td><%= link_to 'Show', sponsor %></td>
    <td><%= link_to 'Edit', edit_sponsor_path(sponsor) %></td>
    <td><%= link_to 'Destroy', sponsor, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sponsor', new_sponsor_path %>

app/views/sponsors/new.html.erb
<h1>New sponsor</h1>

<%= render 'form' %>

<%= link_to 'Back', sponsors_path %>

app/views/sponsors/show.html.erb
<div id="bodyRightPan">
	<div class="bodyRightPanBlock" style="margin-top:2.5em;">
      <h2>Meetings:</h2>
        <% @sponsor.meetings.each do |c| %>
          <div style="overflow:hidden; padding:0px 1em 1.2em;">
          	<div style="width:100%; border-bottom:1px solid #999;"><%= link_to c.name, c %></div>
          	<div style="float:right;">
          		<div style="float:left;"><center><%=c.start_date.strftime("%m/%d/%Y")%><br /><%=c.start_date.strftime("%I:%M %p")%></center></div>
          		<div style="float:left; padding:0px .75em; vertical-align: middle; line-height: 3em;">&mdash;</div>
          		<div style="float:left;"><center><%=c.end_time.strftime("%m/%d/%Y")%><br /><%=c.end_time.strftime("%I:%M %p")%></center></div>
          	</div></div>
        <% end %>
	</div>
</div>
<h1>Sponsor Details</h1>
<p id="notice"><%= notice %></p>

<p>
  <b>Exhibitor</b>
  <%= @sponsor.exhibitor.name %>
</p>

<p>
  <b>Url:</b>
  <%= @sponsor.url %>
</p>

<p>
  <b>Logo:</b>
  <%= @sponsor.logo %>
</p>


<%= link_to 'Edit', edit_sponsor_path(@sponsor) %> |
<%= link_to 'Back', sponsors_path %>