config/routes.rb
Eventmanager::Application.routes.draw do
  resources :contests

  resources :venues

  resources :meetings

  resources :sponsors

  resources :exhibitors

  resources :exhibitor_categories
  
  root :to => "venues#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Event Manager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="topPan"> <a href="/"><h1>Event Manager</h1></a>
  <p>Manage your events... like a boss!</p>
  <div id="topContactPan"> </div>
  <div id="topMenuPan">
    <div id="topMenuLeftPan"></div>
    <div id="topMenuMiddlePan">
      <ul>
			<li id="home"><a href="/">Home</a></li>
			<li><%= link_to 'Venues', venues_path %></li>
			<li><%= link_to 'Meetings', meetings_path %></li>
			<li><%= link_to 'Sponsors', sponsors_path %></li>
			<li><%= link_to 'Contests', contests_path %>
			<li><%= link_to 'Exhibitors', exhibitors_path %></li>
			<li style="width:134px;"><%= link_to 'Exhibitor Categories', exhibitor_categories_path, :style => "width:134px;" %></li>
      </ul>
    </div>
    <div id="topMenuRightPan"></div>
  </div>
</div>
<div id="bodyPan">
  <div id="bodyLeftPan">

    <%= yield %>

  </div>
  <!--div id="bodyRightPan">
    <h2><span>few</span> tips</h2>
    <ul>
      <li><a href="http://www.free-css.com/">lorem ipsum dolor sit</a> </li>
      <li><a href="http://www.free-css.com/">Amet, consectetuer</a> </li>
      <li><a href="http://www.free-css.com/">Amet, consectetuer</a> </li>
      <li><a href="http://www.free-css.com/">Bibendum nunc. Lorem</a> </li>
      <li><a href="http://www.free-css.com/">Ipsum dolor sit amet, </a> </li>
      <li><a href="http://www.free-css.com/">Consectetuer adipiscinrt.</a> </li>
      <li><a href="http://www.free-css.com/">Integer porta enim vel mi.</a> </li>
      <li><a href="http://www.free-css.com/">Vivamus at mi.Ut</a> </li>
    </ul>
    <h3><span>latest</span> updates</h3>
    <p class="boldtext">on 03rd october 2006</p>
    <p>lorem ipsum dolor sit Ametert, consectetue Adipiscingelitedo mol Bibendum</p>
    <p class="more"><a href="http://www.free-css.com/">more</a></p>
    <p class="boldtext">on 03rd october 2006</p>
    <p>lorem ipsum dolor sit Ametert, consectetue Adipiscingelitedo mol Bibendum</p>
    <p class="more"><a href="http://www.free-css.com/">more</a></p>
  </div-->
</div>
<div id="footermainPan">
  <div id="footerPan">
    <ul>
			<li id="home"><a href="/">Home</a></li>
			<li><%= link_to 'Venues', venues_path %></li>
			<li><%= link_to 'Meetings', meetings_path %></li>
			<li><%= link_to 'Sponsors', sponsors_path %></li>
			<li><%= link_to 'Contests', contests_path %>
			<li><%= link_to 'Exhibitors', exhibitors_path %></li>
			<li style="width:154px;"><%= link_to 'Exhibitor Categories', exhibitor_categories_path, :style => "width:154px;" %></li>
    </ul>
    <p class="copyright">©Aint A Saint Productions. All right reserved.</p>
    <!--ul class="templateworld">
      <li>design by:</li>
      <li><a href="http://www.templateworld.com" target="_blank">Template World</a></li>
    </ul-->

  </div>
</div>



</body>
</html>